name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit:
    name: Unit Tests (Vitest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (optional)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script; skipping."
          fi

      - name: Unit tests (Vitest)
        run: npm run test

  e2e:
    name: E2E Tests (Playwright)
    needs: unit
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Start Vite dev server on 5173 in the background
      - name: Start dev server
        run: |
          npm run dev &
          echo $! > devserver.pid
      - name: Wait for dev server
        run: npx wait-on http://127.0.0.1:5173

      - name: Run E2E tests (Playwright)
        env:
          # Playwright uses baseURL from playwright.config.ts (http://localhost:5173)
          CI: "true"
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Stop dev server
        if: always()
        run: |
          if [ -f devserver.pid ]; then
            kill $(cat devserver.pid) || true
          fi